[package]
name = "spdk-core"
version = "0.0.0"
edition.workspace = true
repository.workspace = true
publish = false

[lib]
crate-type = ["lib", "staticlib", "cdylib"]

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
bitcoin.workspace = true
futures.workspace = true
serde.workspace = true
silentpayments.workspace = true

[lints]
workspace = true