[package]
name = "backend-blindbit-v2"
version = "0.1.0"
edition = "2024"
repository.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
spdk-core.workspace = true

anyhow.workspace = true
bitcoin.workspace = true
futures.workspace = true
tonic = "0.14.6"
prost = "0.14.4"
tonic-prost = "0.14.6"
hex = "0.4"

[build-dependencies]
tonic-prost-build = "0.14.6"

[dev-dependencies]
tokio = { version = "1.52.3", features = ["rt-multi-thread"] }
